### ISSUE TITLE
MacOS builds do not work; deployment broken

### ISSUE THREAD

**Issue by msyriac** [simonsobs/pixell#214]
We are not able to deploy pip binary wheels because of the following error
```
C compiler cannot create executables
```
returned by `gcc` on MacOS in `cibuildwheel`. See this example log:  https://pastebin.com/yUrMQQuj

**Comment by JBorrow** [comment]
Thought I'd take a quick look here to see if there's something quick - seems like the problem here is actually a lack of ability to link to -lomp (i.e. it is in the linking not the compilation step). Could be because the ld that's getting chosen is for some reason the default MacOS one (that does not ship with OMP support for some reason) instead of the gcc one. You may have some success setting `export LD=gcc-11` and trying that?

**Comment by msyriac** [comment]
Welcome to pixell dev :) The above output was on the https://github.com/simonsobs/pixell/tree/fix_ci branch where I made some changes. I think the main branch encountered a broken link (I don't remember exactly where now, and I don't like how Github Actions deletes logs pretty quickly).  If you want to dig in, I've given you write access, so you could work off branches and trigger CI on Github Actions.
