### ISSUE TITLE
Installing Problem

### ISSUE THREAD

**Issue by emilymmoser** [simonsobs/pixell#27]
* Python version: 2.7
* Operating System: macOS High Sierra 10.13.6

Hello,
I am trying to download pixell but am having issues. 

What I Did:
I cloned the repository, then tried pip install -e . but it used clang so then I tried CC=gcc-8 pip install -e .

This resulted in a somewhat long error found at: https://pastebin.com/kfYWvr7y
including:

_In file included from cython/sharp.c:569:
    cython/csharp.h:1:10: fatal error: sharp.h: No such file or directory_

I checked that the "sharp" files are indeed there, so I tried to re-download libsharp but this resulted in the same error. Are there known problems and solutions to easily installing pixell?

**Comment by emilymmoser** [comment]
Here is the pastebin of the long output, with the gfortran command in the beginning: https://pastebin.com/AiDFq1XJ

**Comment by msyriac** [comment]
Ok, the relevant error is pretty early on in line 18.

```
scripts/install_libsharp.sh: line 7: aclocal: command not found
scripts/install_libsharp.sh: line 8: ./configure: No such file or directory
```

This happens because you are missing the `automake` dependency. This is listed in the dependencies on README, but it's easy to miss that because of how uninformative the installation is when `aclocal` is not found. TODO for me: make aclocal failure more informative.

Could you install `automake` and start from scratch:
http://macappstore.org/automake/

**Comment by emilymmoser** [comment]
Ah yes I see that now, I tried it again and it all works now. Thank you very much!
