### ISSUE TITLE
Install issue on Niagara

### ISSUE THREAD

**Issue by dwhan89** [simonsobs/pixell#63]
* pixell version:   0.5.3
* Python version: Python 3.7.1
* Operating System: Niagara (CentOS Linux)

### Description

I updated to the latest version pixell on Niagara. I pulled the latest version and installed it from the scratch. After the reinstallation, it fails to load `sharp` module.

### What I Did

Here is the list of modules loaded 

```
nsehgal@nia-login03:~/workspace/pixell$ module list

Currently Loaded Modules:
  1) NiaEnv/2018a        3) cmake/3.10.3   5) autotools/2017   7) openmpi/2.1.3
  2) anaconda3/2018.12   4) git/2.16.3     6) intel/2018.2

```

Here is what I did and the error message

```
nsehgal@nia-login05:~/workspace/pixell$ git pull
nsehgal@nia-login05:~/workspace/pixell$ pip uninstall pixell
nsehgal@nia-login05:~/workspace/pixell$ make clean
nsehgal@nia-login05:~/workspace/pixell$ rm -rf _deps
nsehgal@nia-login05:~/workspace/pixell$ python setup.py install --user
nsehgal@nia-login03:~/workspace/pixell$ python -c "from pixell import curvedsky"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfs/fs1/home/r/rbond/nsehgal/workspace/pixell/pixell/curvedsky.py", line 4, in <module>
    from . import sharp
ImportError: /gpfs/fs1/home/r/rbond/nsehgal/workspace/pixell/pixell/sharp.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strchr
```

**Comment by msyriac** [comment]
Are you following the intel install directions? Can you post the full output of "python setup.py build_ext -i --fcompiler=intelem --compiler=intelem" for a fresh copy? If you follow the development workflow, you can run "py.test" after to catch any issues.

I have stopped using Intel on niagara because of an openmp conflict that arises when using h5py (which I haven't been able to compile with Intel compilers).

**Comment by dwhan89** [comment]
Yeah, I tried "python setup.py build_ext -i --fcompiler=intelem --compiler=intelem" as well, but I couldn't get it working. I finally made it work by compiling both libsharp and pixell with gnu compilers; I used "CC=gcc OMPI_CC=gcc python setup.py install --user"

I am still not sure why it wasn't working out of the box. But I think it is fine for now.

**Comment by msyriac** [comment]
Ok. If you're switching to gnu, then you should make sure your environment is free of Intel stuff, and that everything is recompiled with gnu. Otherwise you'll get (wrong) values in your arrays that depend on OMP_NUM_THREADS due to both Intel and gnu openmp being loaded at the same time. (This is a nasty, generic issue that is independent of pixell). "py.test" in pixell can check for most versions of these conflicts.

**Comment by dwhan89** [comment]
Awesome, sure, I will try that. 

I will close the issue.
